### ISSUE TITLE
Fetch events from FIRST

### ISSUE THREAD

**Issue by jschool504** [first-recon/recon-app#11]
Concept
====
Adding events by hand is an unfun and tedious activity. It would be much easier for the user to simply select their current tournament from a list of tournaments automatically created by FIRST.

## Todo
- [x] Create service to scrape event data from FIRST.
- [x] Create Postgres database and table to store event data in.
- [x] Create api to retrieve data for app.
- [x] Fetch event data in app.
- [ ] Implement filtering for tournaments.
